- name: Output hello message
  debug:
    msg: "Hello, I'm going to install: mariadb-server mariadb-client"

- name: Install package
  ansible.builtin.package:
    name: "{{sql_pkg}}"
    state: present
    update_cache: yes

- name: Start service
  service:
    name: "{{sql_svc}}"
    state: started
    enabled: yes


    