Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.synced_folder ".", "/vagrant"
    dev.vm.network "private_network", ip: "192.168.56.100"
    dev.vm.network "forwarded_port", guest: 80, host: 8080 
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.synced_folder ".", "/vagrant"
    prod.vm.network "private_network", ip: "192.168.56.101"
    prod.vm.network "forwarded_port", guest: 80, host: 8081 
  end
end
