Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.synced_folder ".", "/vagrant"
    server.vm.network "public_network", ip: "192.168.56.100"
    server.vm.provision "shell", path: "server.sh"
  end

  config.vm.define "store" do |store|
    store.vm.hostname = "store"
    store.vm.synced_folder ".", "/vagrant"
    store.vm.network "public_network", ip: "192.168.56.101"
    store.vm.provision "shell", path: "store.sh" 
  end

end
